### ISSUE TITLE
cache invalidation

### ISSUE THREAD

**Issue by reedstrm** [openstax/cnx-publishing#138]
post-publication cooking should probably do something about invalidating the reverse-proxy cache.
This might need additional config to tell publishing where the cache lives, or not: the presumption 
would be that the archive-fetch APIs are impacted, so they could be 'prefetched' since I think we already tell publishing what it's external API hostname is, and we can be sure to configure varnish to accept PURGE requests from wherever publishing is installed.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
