### ISSUE TITLE
Metadata should be updated when pushing to the database

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-publishing#141]
Currently, modifying the metadata doesn't translate in a change in the database.

**Comment by pumazi** [comment]
@helenemccarron Is this still the case? Can you give a short example of where this is an issue? If this has for whatever reason been resolved, please close this issue. Thanks.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
