### ISSUE TITLE
Get tests to pass on travis default Linux environment (trusty)

### ISSUE THREAD

**Issue by karenc** [openstax/cnx-publishing#168]
[Travis is migrating all repositories using the default Linux configuration from Ubuntu Precise to Trusty.](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming)

Importing cnx-archive in triggers does not seem to be working on trusty:
https://travis-ci.org/Connexions/cnx-publishing/builds/257220432

So the [temporary solution](https://github.com/Connexions/cnx-publishing/pull/167) was to run our tests on Precise, but we should probably fix .travis.yml so we can use the default environment.

**Comment by karenc** [comment]
The problem seems to be on Trusty, postgres is not on the same machine as cnx-archive (may be it's in a docker container?).  That means even though we added the virtualenv site packages paths to postgres, postgres cannot find our packages.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
