### ISSUE TITLE
Make channel processing and worker  code more queue aware

### ISSUE THREAD

**Issue by reedstrm** [openstax/cnx-publishing#172]
Extend the channel processor to do more than fire-and-forget messages, and the workers can report more status. For example, avoid double en-queuing  baking - if the same module_ident and and same recipe are present, either pending or baking, don't send again. For the workers, probably need a in-process queue, that receives a message from the worker indication which module_ident and recipe fileid is in flight, by which processid, so we can cleanup the DB statusid to be reliable (i.e. # of "processing" states should match this queue. Add a "pending" state for the existing queue (instead of "processing"), that have not ye been picked up by a worker. Hmm, perhaps we should just leave the stateid at 5 "post-publication" and on startup the channel processor makes sure there is a ticket in the queue for every one of those.  Channel processor should also 'peek' at the queue for version info: if a newer version of a given book is being enqueued, it should 'jump the queue' in front of earlier versions of itself.

**Comment by reedstrm** [comment]
So, several things here:

**Comment by reedstrm** [comment]
Eventually, we're going to have more than one type of worker, so having more feedback as to what's happening would be good. (baking, PDF gen, etc.)

**Comment by reedstrm** [comment]
I did a little of the simple bits: https://github.com/Connexions/cnx-publishing/pull/174

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
