### ISSUE TITLE
baking monitoring tool=> add a browser favicon

### ISSUE THREAD

**Issue by kerwinso** [openstax/cnx-publishing#192]
cuz it would look cool, especially in a pinned browser tab

**Comment by kerwinso** [comment]
maybe something like this? http://static0.srcdn.com/wp-content/uploads/gob-bluth.jpg @brittweinstein

**Comment by brittweinstein** [comment]
If this were to become the real deal, I would have that tab open the rest of my life.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
