### ISSUE TITLE
initdb has SQL permissions issue

### ISSUE THREAD

**Issue by reedstrm** [openstax/cnx-publishing#49]
the initdb command uses the connection info from the ini provided. If this is a properly least privileged user, it will fail to create the plpythonu methods. If you temp change the connection to a superuser, then you get the wrong owner on the tables. So, work around is to grant the right user superuser privs, briefly. Correct solution is probably to take a parameter for what superuser to connect as, then extract the existing user and make sure the created objects are owned by that user.

**Comment by rich-hart** [comment]
I was going to give this issue a shot, unless its something best suited for someone else because it's high priority and they can do it faster.

**Comment by pumazi** [comment]
Sounds like a good idea. I'm sure Ross will appreciate it.

**Comment by pumazi** [comment]
This isse only appears in cnx-publishing repo/project, but the implementation need to happen in both cnx-publishing and cnx-archive. It may be easier to address in cnx-archive before cnx-publishing. Or at least that's how I would probably tackle the issue.

**Comment by pumazi** [comment]
See also, Connexions/cnx-deploy#267

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
