### ISSUE TITLE
Resubmission of the same EPUB is possible

### ISSUE THREAD

**Issue by pumazi** [openstax/cnx-publishing#53]
It is possible to submit the same content twice or more. This means you could potentially end up with multiple copies of the same content.

If this isn't correct, it could cause issue related to revisions if we (or more likely third-parties) don't update the identifiers in the epub when submitting a revision. This could mean that the revision would be entered as new content.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
