### ISSUE TITLE
Incorrect content identifier mapping on publication

### ISSUE THREAD

**Issue by pumazi** [openstax/cnx-publishing#61]
It appears that the identifiers mapping, found in the initial publication response, is incorrect. The identifiers look to be keyed by the new uuid and valued with ident-hash. The value is correct. However, the key should be the identifier found in the epub filename.

This only affects third-party publications, since the mapping isn't used by cnx-authoring.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
